// components/link.tsx
import type { FC } from 'react';
import type { LinkProps as NextLinkProps } from 'next/link';
import NextLink from 'next/link';

type ExternalLinkProps = React.DetailedHTMLProps<React.AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>;

type InternalLinkProps = Omit<NextLinkProps, 'href' | 'passHref'> & { href: string; children: React.ReactNode };

type LinkProps = ExternalLinkProps | InternalLinkProps;

const Link: FC<LinkProps> = (props) => {
  if (props.href?.includes('http')) {
    const { children, href, ...externalProps } = props as ExternalLinkProps;

    return (
      <a href={href} rel="noreferrer" target="_blank" {...externalProps}>
        {children}
      </a>
    );
  }

  const { children, href, ...internalProps } = props as InternalLinkProps;

  return (
    <NextLink href={href} passHref {...internalProps}>
      <a>{children}</a>
    </NextLink>
  );
};

export type { LinkProps };
export { Link };

// src/components/link.tsx
import { component$, Slot } from '@builder.io/qwik';

type LinkProps = Partial<Omit<HTMLAnchorElement, 'rel' | 'target'>>;

const Link = component$<LinkProps>(({ href, ...props }) => {
  if (href.startsWith('http')) {
    return (
      <a {...props} href={href} rel="noreferrer" target="_blank">
        <Slot />
      </a>
    );
  }

  return (
    <a {...props} href={href}>
      <Slot />
    </a>
  );
});

export type { LinkProps };
export { Link };
